### ISSUE TITLE
FAIL TypeError: base64.charCodeAt is not a function

### ISSUE THREAD

**Issue by ybbarng** [herrjemand/FIDO2WebAuthnSeries#1]
Hello, I tried to use [your usename-less login demo](https://github.com/herrjemand/FIDO2WebAuthnSeries/issues/1#issue-4313610250), but the login process is not working with the following error:
```
FAIL TypeError: base64.charCodeAt is not a function
    at Object.decode (base64url-arraybuffer.js:50)
    at preformatGetAssertReq (helpers.js:119)
    at UsernamelessExample.html:88
```

I hope it will fix soon so that I can get the experience of username-less login.
Thank you.

**Comment by yackermann** [comment]
Resolved. Thanks for submitting the issue!
