### ISSUE TITLE
UsernamelessExample login fails on Edge and Firefox

### ISSUE THREAD

**Issue by git14** [herrjemand/FIDO2WebAuthnSeries#2]
Windows 1903, Edge v44, Firefox 67

Register works, Login fails:

Edge error message: `FAILTypeError: Cannot convert null or undefined to object`
Firefox error message `FAILTypeError: getAssert.allowCredentials is undefined`

**Comment by hrchu** [comment]
+1
Register works with yubikey but does not work with Touch ID.
Login does not work in Edge for Mac Version 76.0.182.6 (Official build) Dev (64-bit)

**Comment by yackermann** [comment]
@hrchu Fixed! Sorry for the long wait!
